version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fmfp_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./rust/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./rust:/usr/src/app
  # rust-app:
  #   image: rust:latest
  #   container_name: backend
  #   working_dir: /usr/src/app
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./rust:/usr/src/app
  #   command: cargo run --release

volumes:
  postgres_data:

